# Generated by Django 6.0.7 on 2026-08-03 20:21

import complaints.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'db_table': 'complaints_categorie',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_suivi', models.CharField(editable=False, max_length=20, unique=True)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('adresse_approx', models.CharField(blank=True, max_length=255)),
                ('statut', models.CharField(choices=[('NOUVELLE', 'Nouvelle'), ('RECUE', 'Reçue'), ('AFFECTEE', 'Affectée'), ('EN_COURS', 'En cours'), ('RESOLUE', 'Résolue'), ('CLOTUREE', 'Clôturée'), ('REJETEE', 'Rejetée')], default='NOUVELLE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('date_cloture', models.DateTimeField(blank=True, null=True)),
                ('note_citoyen', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_traitees', to=settings.AUTH_USER_MODEL)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reclamations', to='complaints.categorie')),
                ('citoyen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reclamations_soumises', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_affectees', to='accounts.service')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations', to='accounts.zone')),
            ],
            options={
                'verbose_name': 'Réclamation',
                'verbose_name_plural': 'Réclamations',
                'db_table': 'complaints_reclamation',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fichier', models.FileField(max_length=255, upload_to=complaints.models.chemin_media)),
                ('type_media', models.CharField(choices=[('PHOTO', 'Photo'), ('VIDEO', 'Vidéo')], max_length=10)),
                ('taille_octets', models.PositiveIntegerField()),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('reclamation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='complaints.reclamation')),
            ],
            options={
                'verbose_name': 'Média',
                'verbose_name_plural': 'Médias',
                'db_table': 'complaints_media',
                'ordering': ['date_upload'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueStatut',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ancien_statut', models.CharField(blank=True, max_length=20)),
                ('nouveau_statut', models.CharField(max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('date_changement', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reclamation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='complaints.reclamation')),
            ],
            options={
                'verbose_name': 'Historique de statut',
                'verbose_name_plural': 'Historiques de statut',
                'db_table': 'complaints_historiquestatut',
                'ordering': ['-date_changement'],
            },
        ),
        migrations.AddIndex(
            model_name='reclamation',
            index=models.Index(fields=['statut'], name='ix_reclamation_statut'),
        ),
        migrations.AddIndex(
            model_name='reclamation',
            index=models.Index(fields=['-date_creation'], name='ix_reclamation_date_creation'),
        ),
        migrations.AddIndex(
            model_name='reclamation',
            index=models.Index(fields=['service', 'statut'], name='ix_reclamation_service_statut'),
        ),
        migrations.AddConstraint(
            model_name='reclamation',
            constraint=models.CheckConstraint(condition=models.Q(('note_citoyen__isnull', True), models.Q(('note_citoyen__gte', 1), ('note_citoyen__lte', 5)), _connector='OR'), name='ck_reclamation_note'),
        ),
        migrations.AddConstraint(
            model_name='reclamation',
            constraint=models.CheckConstraint(condition=models.Q(('latitude__gte', -90), ('latitude__lte', 90)), name='ck_reclamation_latitude'),
        ),
        migrations.AddConstraint(
            model_name='reclamation',
            constraint=models.CheckConstraint(condition=models.Q(('longitude__gte', -180), ('longitude__lte', 180)), name='ck_reclamation_longitude'),
        ),
    ]
