# Generated by Django 6.0.7 on 2026-08-03 20:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canal', models.CharField(choices=[('SMS', 'SMS'), ('PUSH', 'Notification push')], max_length=10)),
                ('contenu', models.TextField()),
                ('statut_envoi', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ENVOYE', 'Envoyé'), ('ECHEC', 'Échec')], default='EN_ATTENTE', max_length=20)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('reclamation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='complaints.reclamation')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications_notification',
                'ordering': ['-date_envoi'],
                'indexes': [models.Index(fields=['statut_envoi'], name='ix_notification_statut_envoi')],
            },
        ),
    ]
