# Generated by Django 6.0.7 on 2026-08-03 20:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegleAffectation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priorite', models.IntegerField(default=0, help_text='Priorité décroissante en cas de conflit.')),
                ('active', models.BooleanField(default=True)),
                ('categorie', models.ForeignKey(blank=True, help_text='Laisser vide pour une règle applicable à toutes les catégories.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regles_affectation', to='complaints.categorie')),
                ('service_cible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regles_affectation', to='accounts.service')),
                ('zone', models.ForeignKey(blank=True, help_text='Laisser vide pour une règle applicable à toutes les zones.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regles_affectation', to='accounts.zone')),
            ],
            options={
                'verbose_name': "Règle d'affectation",
                'verbose_name_plural': "Règles d'affectation",
                'db_table': 'assignment_regleaffectation',
                'ordering': ['-priorite'],
                'indexes': [models.Index(fields=['active'], name='ix_regle_active')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('active', True)), fields=('categorie', 'zone'), name='uq_regle_active_categorie_zone')],
            },
        ),
    ]
